const STATUS_OK = 200;
const STATUS_BAD_REQUEST = 400;
const STATUS_UNAUTHROIZED = 401;
const STATUS_FORBIDDEN = 403;
const STATUS_NOT_FOUND = 404;
const STATUS_SERVER_ERROR = 500;
const STATUS_UNPROCESSABLE_ENTITY = 422;

module.exports = {
	STATUS_OK,
	STATUS_BAD_REQUEST,
	STATUS_UNAUTHROIZED,
	STATUS_FORBIDDEN,
	STATUS_NOT_FOUND,
	STATUS_SERVER_ERROR,
	STATUS_UNPROCESSABLE_ENTITY
}